adastra_dir: /home/{your-profile}/adastra/Adastra-17-linux
data_dir: /home/{your-profile}/adastra/data
screenplays_dir: /home/{your-profile}/adastra/screenplays
wordclouds_dir: /home/{your-profile}/adastra/wordclouds
analytics_dir: /home/{your-profile}/adastra/analytics
queries_dir: /home/{your-profile}/adastra/queries
