# Specify the filter on the dataset (using Pandas syntax).
# By default, 'file', 'line_idx', 'speaker', and 'is_optional' are filterable.
# 
# Specify the paths to the images in `{adastra_dir}/game/images`.
# These will be saved with identical pathing in `{wordclouds_dir}`.

- filter: "speaker == 'alexios'"
  images: 
    - sprites/alexios/alexios.png
    - sprites/alexios/alexios-vshocked-e.png
    - sprites/alexios/alexios-shocked.png
    - sprites/alexios/alexios-embarrassed.png
    - sprites/alexios/alexios-angry-e-u.png

- filter: "speaker == 'amicus'"
  images:
    - sprites/amicus/amicus.png
    - sprites/amicus/amicus-tears.png
    - sprites/amicus/amicus-smile.png
    - sprites/amicus/amicus-shocked.png
    - sprites/amicus/amicus-crossed-serious.png
    - sprites/amicus/amicus-angry-n.png
    - illustrations/sleep.png
    - illustrations/amicusend.png
    - illustrations/introspection.png
    - illustrations/dinner1.PNG
    - illustrations/dinner2.PNG
    - illustrations/dinner3.PNG
    - illustrations/dinner4.PNG

- filter: "speaker == 'cassius'"
  images:
    - sprites/cassius/cassius.png
    - sprites/cassius/cassius-angry-u.png
    - sprites/cassius/cassius-paw.png
    - sprites/cassius/cassius-furious.png
    - sprites/cassius/cassius-disappointed-u.png

- filter: "speaker == 'cato'"
  images:
    - sprites/cato/cato.png
    - sprites/cato/cato-bow-v.png
    - sprites/cato/cato-angry-u.png

- filter: "speaker == 'neferu'"
  images:
    - sprites/neferu/neferu.png
    - sprites/neferu/neferu-wink-f.png
    - sprites/neferu/neferu-talking-n.png
    - sprites/neferu/neferu-talking-a.png
    - sprites/neferu/neferu-silly-f-n.png
    - sprites/neferu/neferu-shocked.png
    - sprites/neferu/neferu-fury.png

- filter: "speaker == 'virginia'"
  images:
    - sprites/virginia/virginia.png
    - sprites/virginia/virginia-tilt-p.png
    - sprites/virginia/virginia-annoyed.png
    - illustrations/archives1.png

- filter: "speaker == 'meera'"
  images: 
    - illustrations/meera.png

- filter: "speaker == 'monitor'"
  images:
    - illustrations/monitor.png

- filter: "speaker.isin(['cassius', 'alexios'])"
  images:
    - illustrations/poisoned.png
    - illustrations/alexandcassius.PNG
    - illustrations/alexandcassiuskiss.PNG

- filter: "speaker.isin(['cato', 'neferu'])"
  images:
    - illustrations/nefandcat1.PNG
    - illustrations/nefandcat2.PNG

- filter: "speaker.isin(['amicus', 'neferu'])"
  images:
    - illustrations/amicusandneferu1.png
    - illustrations/amicusandneferu2.png
    - illustrations/amicusandneferu3.png
    - illustrations/backoff2.PNG
    - illustrations/backoff3.PNG

- filter: "~speaker.isnull()"
  images:
    - illustrations/adastra.png
    - illustrations/Adastranl.png

- filter: "file == 'end_game1' & speaker.isin(['amicus', 'marco'])"
  images:
    - illustrations/farewell1.png
    - illustrations/farewell3.png
    - illustrations/wemadeit1.PNG
    - illustrations/wemadeit4.PNG

- filter: "file == 'a3s2'"
  images:
    - illustrations/lastmoment.png

- filter: "file == 'a3s2' & speaker.isin(['amicus', 'internal', 'monitor'])"
  images:
    - illustrations/finalspace.png
    - illustrations/finalspace2.png
    - illustrations/watching.PNG

- filter: "speaker.isin(['amicus', 'marco', 'internal']) & is_optional"
  images:
    - illustrations/amiscene1.png
    - illustrations/amiscene3.png
    - illustrations/ss1.png
    - illustrations/ss3.png
    - illustrations/2ss.png
    - illustrations/2ss3.png
