# Main parameters that affect the run of the script.
settings:

  # Specify the path to the unzipped Adastra folder.
  adastra_dir: /home/jayckaiser/adastra/Adastra-17-linux

  # Specify where the 'adastra' JSONL datasets are stored.
  data_dir: /home/jayckaiser/adastra/data

  # Specify where the wordclouds should be saved.
  wordclouds_dir: /home/jayckaiser/adastra/wordclouds

  # Specify whether the 'adastra.json' or 'adastra_nlp.json' dataset is used here.
  dataset: adastra_nlp

  # Specify which column in the dataframe will be used to populate the wordclouds.
  # - List columns are automatically joined before processing.
  # - Good options are 'line', 'words', or 'content_words'.
  #   * 'line' is the cleaned text of the line.
  #   * 'words' removes punctuation.
  #   * 'content_words' removes punctuation and stop-words, and converts to lowercase.
  text_column: content_words

  # Specify which columns are queryable.
  index_columns:
    - file
    - line_idx
    - speaker
    - is_optional


wordclouds:
  # Define universal wordcloud params here. They can be overwritten in any image below.
  wordcloud_args:
    max_words: 2000
    max_font_size: 40
    mode: RBG
    background_color: black
    repeat: True
    relative_scaling: 0.5
    random_state: 42

  # Create one wordcloud per image.
  # - By default, the key is the name of both the input and output image.
  #   (If the input image is different, specify a 'file' subkey.)
  images:

    # Alexios
    sprites/alexios/alexios:
      where: "speaker = 'alexios'"
    sprites/alexios/alexios-vshocked-e:
      where: "speaker = 'alexios'"
    sprites/alexios/alexios-shocked:
      where: "speaker = 'alexios'"
    sprites/alexios/alexios-embarrassed:
      where: "speaker = 'alexios'"
    sprites/alexios/alexios-angry-e-u:
      where: "speaker = 'alexios'"

    # Amicus
    sprites/amicus/amicus:
      where: "speaker = 'amicus'"
    sprites/amicus/amicus-tears:
      where: "speaker = 'amicus'"
    sprites/amicus/amicus-smile:
      where: "speaker = 'amicus'"
    sprites/amicus/amicus-shocked:
      where: "speaker = 'amicus'"
    sprites/amicus/amicus-crossed-serious:
      where: "speaker = 'amicus'"
    sprites/amicus/amicus-angry-n:
      where: "speaker = 'amicus'"
    illustrations/sleep:
      where: "speaker = 'amicus'"
    illustrations/amicusend:
      where: "speaker = 'amicus'"
    illustrations/introspection:
      where: "speaker = 'amicus'"
    illustrations/dinner1:
      where: "speaker = 'amicus'"
    illustrations/dinner2:
      where: "speaker = 'amicus'"
    illustrations/dinner3:
      where: "speaker = 'amicus'"
    illustrations/dinner4:
      where: "speaker = 'amicus'"

    # Cassius
    sprites/cassius/cassius:
      where: "speaker = 'cassius'"
    sprites/cassius/cassius-angry-u:
      where: "speaker = 'cassius'"
    sprites/cassius/cassius-paw:
      where: "speaker = 'cassius'"
    sprites/cassius/cassius-furious:
      where: "speaker = 'cassius'"
    sprites/cassius/cassius-disappointed-u:
      where: "speaker = 'cassius'"

    # Cato
    sprites/cato/cato:
      where: "speaker = 'cato'"
    sprites/cato/cato-bow-v:
      where: "speaker = 'cato'"
    sprites/cato/cato-angry-u:
      where: "speaker = 'cato'"

    # Neferu
    sprites/neferu/neferu:
      where: "speaker = 'neferu'"
    sprites/neferu/neferu-wink-f:
      where: "speaker = 'neferu'"
    sprites/neferu/neferu-talking-n:
      where: "speaker = 'neferu'"
    sprites/neferu/neferu-talking-a:
      where: "speaker = 'neferu'"
    sprites/neferu/neferu-silly-f-n:
      where: "speaker = 'neferu'"
    sprites/neferu/neferu-shocked:
      where: "speaker = 'neferu'"
    sprites/neferu/neferu-fury:
      where: "speaker = 'neferu'"

    # Virginia
    sprites/virginia/virginia:
      where: "speaker = 'virginia'"
    sprites/virginia/virginia-tilt-p:
      where: "speaker = 'virginia'"
    sprites/virginia/virginia-annoyed:
      where: "speaker = 'virginia'"
    illustrations/archives1:
      where: "speaker = 'virginia'"

    # Meera 
    illustrations/meera:
      where: "speaker = 'meera'"

    # Monitor
    illustrations/monitor:
      where: "speaker == 'monitor'"

    # Cassius and Alexios
    illustrations/poisoned:
      where: "speaker IN ('cassius', 'alexios')"
    illustrations/alexandcassius:
      where: "speaker IN ('cassius', 'alexios')"
    illustrations/alexandcassiuskiss:
      where: "speaker IN ('cassius', 'alexios')"

    # Cato and Neferu
    illustrations/nefandcat1:
      where: "speaker IN ('cato', 'neferu')"
    illustrations/nefandcat2:
      where: "speaker IN ('cato', 'neferu')"

    # Amicus and Neferu
    illustrations/amicusandneferu1:
      where: "speaker IN ('amicus', 'neferu')"
    illustrations/amicusandneferu2:
      where: "speaker IN ('amicus', 'neferu')"
    illustrations/amicusandneferu3:
      where: "speaker IN ('amicus', 'neferu')"
    illustrations/backoff2:
      where: "speaker IN ('amicus', 'neferu')"
    illustrations/backoff3:
      where: "speaker IN ('amicus', 'neferu')"

    # All text
    illustrations/adastra:
      where: "speaker IS NOT NULL"
    illustrations/Adastranl:
      where: "speaker IS NOT NULL"

    # Amicus and Marco in end-game
    illustrations/farewell1:
      where: "file = 'end_game1' AND speaker IN ('amicus', 'marco')"
    illustrations/farewell3:
      where: "file = 'end_game1' AND speaker IN ('amicus', 'marco')"
    illustrations/wemadeit1:
      where: "file = 'end_game1' AND speaker IN ('amicus', 'marco')"
    illustrations/wemadeit4:
      where: "file = 'end_game1' AND speaker IN ('amicus', 'marco')"

    # In Act 3 Scene 2
    illustrations/lastmoment:
      where: "file = 'a3s2'"

    # Amicus & Internal Narration & Monitor in Act 3 Scene 2
    # (This could be better filtered by line number.)
    illustrations/finalspace:
      where: "file = 'a3s2' AND speaker IN ('amicus', 'internal', 'monitor')"
      wordcloud_args:
        background_color: white
    illustrations/finalspace2:
      where: "file = 'a3s2' AND speaker IN ('amicus', 'internal', 'monitor')"
      wordcloud_args:
        background_color: white
    illustrations/watching:
      where: "file = 'a3s2' AND speaker IN ('amicus', 'internal', 'monitor')"
      wordcloud_args:
        background_color: white

    # Amicus & Marco & Internal Narration in optional paths ;)
    illustrations/amiscene1:
      where: "speaker IN ('amicus', 'marco', 'internal') AND is_optional"
      wordcloud_args:
        background_color: white
    illustrations/amiscene3:
      where: "speaker IN ('amicus', 'marco', 'internal') AND is_optional"
      wordcloud_args:
        background_color: white
    illustrations/ss1:
      where: "speaker IN ('amicus', 'marco', 'internal') AND is_optional"
      wordcloud_args:
        background_color: white
    illustrations/ss3:
      where: "speaker IN ('amicus', 'marco', 'internal') AND is_optional"
      wordcloud_args:
        background_color: white
    illustrations/2ss:
      where: "speaker IN ('amicus', 'marco', 'internal') AND is_optional"
      wordcloud_args:
        background_color: white
    illustrations/2ss3:
      where: "speaker IN ('amicus', 'marco', 'internal') AND is_optional"
      wordcloud_args:
        background_color: white
